### ISSUE TITLE
Erro ao apagar número de cartão de Crédito - Firefox

### ISSUE THREAD

**Issue by eduardopc** [payu-br/magento-transparente#26]
Não é possível copiar e colar um número de cartão de crédito no campo 'Número do cartão'. Assim como não é possível deletar um valor previamente digitado.

**Comment by eduardopc** [comment]
Necessário liberar as teclas 'Ctrl + V', 'Tab', 'Home' e 'End' para o campo 'Número do Cartão'.

**Comment by viniciustaveira** [comment]
Testes ok.
