### ISSUE TITLE
Verificar desconto quando selecionar a forma de pagamento

### ISSUE THREAD

**Issue by ftgouveia** [payu-br/magento-transparente#32]
Ao selecionar a forma de pagamento, verificar se a forma de pagamento possui desconto e atualizar os valores de acordo com os parâmetros aplicados.

Cenário: OSC - Ao selecionar uma forma de pagamento, exemplo boleto, temos que aplicar o desconto configurado no magento, se alteramos a forma de pagamento para cartão deve ser retirado ou aplicado o desconto configurado para esta mesma forma de pagamento, atualmente não está atualizando os valores para fechamento da compra.

**Comment by Delorien** [comment]
Done
